import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-8 flex flex-col min-h-screen justify-between`}
      >
        <div>
          <header className="text-center text-sm text-gray-500 py-8">
            <nav>
              <Link href="/">Home</Link>
            </nav>
          </header>
          {children}
        </div>
        <footer className="text-center text-sm text-gray-500 py-8">
          Made with Next.js 16 and React 19 - By O. Wolfson for{" "}
          <Link className="underline text-pink-600" href="https://mdxblog.io">
            MDXBlog.io
          </Link>
        </footer>
      </body>
    </html>
  );
}
